# Generated by Django 5.1.4 on 2026-03-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('headline', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['symbol', 'published_at'], name='market_data_symbol_fa0e5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('ETF', 'ETF'), ('CRYPTO', 'Crypto'), ('OPTION', 'Option')], default='STOCK', max_length=10)),
                ('open', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('close', models.DecimalField(decimal_places=6, max_digits=15)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('ALPACA', 'Alpaca'), ('YFINANCE', 'yFinance')], default='YFINANCE', max_length=10)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_data_symbol_b92df2_idx')],
            },
        ),
    ]
