# Generated by Django 5.1.4 on 2026-03-05 18:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_providers', models.JSONField(default=list)),
                ('strategies', models.JSONField(default=list)),
                ('risk_tolerance', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=6)),
                ('max_position_size_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('analysis_interval_minutes', models.IntegerField(default=30)),
                ('watchlist', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_config', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Strategy Config',
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('CLAUDE', 'Claude'), ('OPENAI', 'OpenAI'), ('GEMINI', 'Gemini')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('ETF', 'ETF'), ('CRYPTO', 'Crypto'), ('OPTION', 'Option')], default='STOCK', max_length=10)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('REBALANCE', 'Rebalance')], max_length=10)),
                ('confidence', models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=4)),
                ('quantity_suggested', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=15)),
                ('price_target', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('reasoning', models.TextField()),
                ('analysis_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', 'status'], name='ai_advisor__portfol_9ebe89_idx'), models.Index(fields=['symbol', 'created_at'], name='ai_advisor__symbol_7cd735_idx')],
            },
        ),
    ]
