# Generated by Django 5.1.4 on 2026-03-07 11:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyconfig',
            name='auto_trade',
            field=models.BooleanField(default=False, help_text='When enabled, high-confidence AI recommendations are executed automatically.'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='auto_trade_min_confidence',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.700'), help_text='Minimum confidence (0–1) required for auto-execution.', max_digits=4),
        ),
    ]
